<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<%
try{
	java.util.ArrayList al = (java.util.ArrayList)request.getAttribute("TransList");
	
		test.accounttransfer.AccountTransferCom atc = (test.accounttransfer.AccountTransferCom) al.get(0);
 %>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Transaction Listing</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="trres/top.png" alt="">
	<div id="form_container">
	
		<h1><a>Transaction Listing</a></h1>
		<form id="form_685107" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Account Transfer Result</h2>
			<p>Search Transactions Based on Date</p>
		</div>						
			<ul >
			
					<li class="section_break">
			<h3>From Account Number : <%= atc.getDebitAccount() %></h3>
			<p></p>
		</li>		<li class="section_break">
			<h3>To Account Number : <%= atc.getCreditAccount() %></h3>
			<p></p>
		</li>		<li class="section_break">
			<h3>Amount :<%= atc.getTransAmount() %></h3>
			<p></p>
		</li>		<li class="section_break">
			<h3>Remarks : <%= request.getParameter("TransRermarks") %></h3>
			<script type="javascript"> alert(hacked);</script>
			<p></p>
		</li>		<li class="section_break">
			<h3>Transaction ID : <%= atc.getTransId() %></h3>
			<p></p>
		</li>		<li class="section_break">
			<h3>Status : Success </h3>
			<p></p>
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="685107" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>
<%
}catch (Exception ex){
		ex.getStackTrace();
	}
	


 %>
