<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<%@ page import="java.util.*" %>
<%@ page import="com.fileupload.*" %>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>File Upload</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Command Injection</a></h1>
		<form id="form_891659" class="appnitro"  method="post" action="/secureCodingTrainingWeb/CommandInjection.svl">
					<div class="form_description">
			<h2>Command Injection</h2>
			<p>This is a screen to test commands</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Customer Code </label>
		<div>
			<input id="element_1" name="CustomerCode" class="element text medium" type="text" maxlength="255" value=""/> 
			<input id="saveForm" class="button_text" type="submit" name="Search" value="Search" /> 
		</div> 
		</li>
<%

	ArrayList fileList = new ArrayList();
	if(request.getAttribute("FileList")!= null )
		fileList = (ArrayList)request.getAttribute("FileList");
		if (fileList.size() > 0){
		
 %>		
				<li id="li_2" >
		<label class="description" for="element_2">Choose the File To Approve </label>
		
<%
	for(int i=0;i < fileList.size();i++)
		{
			FileUploadCom atc = (FileUploadCom) fileList.get(i);

 %>		
 <br/><span>
			<input id="element_2_1" name="FileName" class="element radio" type="radio" value="<%= atc.getFileName() %>" />
<label class="choice" for="element_2_1"><%= atc.getFileName() %></label>
	</span>
<%
	}
 %>
	 
		</li>
<%
		
	}			
%>
					<li class="buttons">
			    <input type="hidden" name="form_id" value="891659" />
			    
				<input id="saveForm" class="button_text" type="submit" name="Approve" value="Approve" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>