<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Account Transfer</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	<%   /*This Code is written by Raghu SV*/ %>
		<h1><a>Account Transfer</a></h1>
		<form id="form_682209" class="appnitro"  method="post" action="/secureCodingTrainingWeb/AccountTransfer.svl">
		
		
					<div class="form_description">
			<h2>Account Transfer</h2>
			<p>Sample Account Transfer Page</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Enter Source Account (Debit) </label>
		<div>
			<input id="element_1" name="DebitAccount" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Enter Destination Account (Credit) </label>
		<div>
			<input id="element_2" name="CreditAccount" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Amount to be transfered </label>
		<div>
			<input id="element_3" name="TransAmount" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_4" >
		<label class="description" for="element_4">Transaction Instruction </label>
		<div>
			<textarea id="element_4" name="TransRermarks" class="element textarea medium"></textarea> 
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="682209" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>